# -*- coding: utf-8 -*-
"""Aviato_272.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19RDtRxbTRNaayr286zkBXZ3QBs5p3144
"""

import pandas as pd
import sys
dic = {}
games = pd.read_csv('/Users/aravindthonupunuri/Downloads/nfl-big-data-bowl-2022/games.csv')
players = pd.read_csv('/Users/aravindthonupunuri/Downloads/nfl-big-data-bowl-2022/players.csv')

groupBySeason = games.groupby('season')['gameId'].count()
groupBySeason= pd.DataFrame(groupBySeason)
# groupBySeason.to_json()
# print(groupBySeason.to_json())
dic["groupBySeason"] = groupBySeason.to_json()

groupByWeek = games.groupby('week')['gameId'].count()
groupByWeek= pd.DataFrame(groupByWeek)
groupByWeek.to_json()
dic["groupByWeek"] = groupByWeek.to_json()
groupByGameTimeEastern = games.groupby('gameTimeEastern')['gameId'].count()
groupByGameTimeEastern= pd.DataFrame(groupByGameTimeEastern)
groupByGameTimeEastern.to_json()

groupByPlayersWeight = players.groupby('weight')['nflId'].count()
groupByPlayersWeight = pd.DataFrame(groupByPlayersWeight)
groupByPlayersWeight.to_json()


print(dic)