# -*- coding: utf-8 -*-
"""Aviato_272.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19RDtRxbTRNaayr286zkBXZ3QBs5p3144
"""

import pandas as pd
import sys,json
games = pd.read_csv('./games.csv')
players = pd.read_csv('./players.csv')
plays_df = pd.read_csv('./plays.csv')

data = json.loads(sys.argv[1])

if "week" == data:
    groupByWeek = games.groupby('week')['gameId'].count()
    groupByWeek= pd.DataFrame(groupByWeek)
    print(groupByWeek.to_json())

elif "season" == data:
    groupBySeason = games.groupby('season')['gameId'].count()
    groupBySeason= pd.DataFrame(groupBySeason)
    print(groupBySeason.to_json())

elif "gameTimeEastern" == data:
    groupByGameTimeEastern = games.groupby('gameTimeEastern')['gamesId'].count()
    groupByGameTimeEastern= pd.DataFrame(groupByGameTimeEastern)
    print(groupByGameTimeEastern.to_json())

elif "headToHead"== data:
    team1 = json.loads(sys.argv[2])
    team2 = json.loads(sys.argv[3])
    groupByHeadToHead = games[(games["homeTeamAbbr"]==team1) & (games["visitorTeamAbbr"]==team2)]
    print(len(groupByHeadToHead))

elif "weight" == data:
    groupByPlayersWeight = players.groupby('weight')['nflId'].count()
    groupByPlayersWeight = pd.DataFrame(groupByPlayersWeight)
    print(groupByPlayersWeight.to_json())

elif "height" == data:

    groupByPlayersHeight = players.groupby('height')['nflId'].count()
    groupByPlayersHeight = pd.DataFrame(groupByPlayersHeight)
    print(groupByPlayersHeight.to_json())

elif data == "teams":
    teams = games.homeTeamAbbr.unique()
    print(teams)

elif data == "position":
    playersByPosition = players.groupby("Position")['nflId'].count()
    playersByPosition = pd.DataFrame(playersByPosition)
    print(playersByPosition.to_json())


elif data == "playsbyquarter":
    playsByquarter  = plays.groupby("quarter")['gameId'].count()
    playsByquarter = pd.DataFrame(playsByquarter)
    print(playsByquarter.to_json())


else:
    raise Exception("Unkown stuff")

