# -*- coding: utf-8 -*-
"""Aviato_272.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19RDtRxbTRNaayr286zkBXZ3QBs5p3144
"""

import pandas as pd
import sys,json
dic = {}
games = pd.read_csv('/Users/aravindthonupunuri/Downloads/nfl-big-data-bowl-2022/games.csv')
players = pd.read_csv('/Users/aravindthonupunuri/Downloads/nfl-big-data-bowl-2022/players.csv')

data = json.loads(sys.argv[1])
    
if "week" == data:
    groupByWeek = games.groupby('week')['gameId'].count()
    groupByWeek= pd.DataFrame(groupByWeek)
    print(groupByWeek.to_json())

elif "season" == data:
    groupBySeason = games.groupby('season')['gameId'].count()
    groupBySeason= pd.DataFrame(groupBySeason)
    print(groupBySeason.to_json())

elif "gameTimeEastern" == data:
    groupByGameTimeEastern = games.groupby('gameTimeEastern')['gamesId'].count()
    groupByGameTimeEastern= pd.DataFrame(groupByGameTimeEastern)
    print(groupByGameTimeEastern.to_json())

elif "weight" == data:
    groupByPlayersWeight = players.groupby('weight')['nflId'].count()
    groupByPlayersWeight = pd.DataFrame(groupByPlayersWeight)
    print(groupByPlayersWeight.to_json())
    
else:
    raise Exception("Unkown stuff")

